// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// This project keeps secrets in `.env.local`, which Next.js loads on its own but
// `dotenv/config` does not — it only reads `.env`. Without this the Prisma CLI
// starts with no DATABASE_URL and every command fails on a missing datasource.
import { config } from "dotenv";
config({ path: [".env.local", ".env"] });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
